### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by ChitChips** [at-internet/atinternet-ios-swift-sdk#1]
Do you have any plans to support Carthage?

Currently, when we are trying to build your projet with Carthage, we have this error : 

Error Domain=NSCocoaErrorDomain Code=3840 "Unexpected character / at line 1" UserInfo={NSDebugDescription=Unexpected character / at line 1, kCFPropertyListOldStyleParsingError=Error Domain=NSCocoaErrorDomain Code=3840 "Expected terminating ')' for array at line 1250" UserInfo={NSDebugDescription=Expected terminating ')' for array at line 1250}}

**Comment by ghost** [comment]
No, today we don't have any plans to support Carthage.

**Comment by evixar** [comment]
Hello,

We tested Carthage and added a documentation in the readme to explain how to integrate our SDK with it.

Hope this helps,

Regards
