### ISSUE TITLE
'Tracker/Crash.h' file not found

### ISSUE THREAD

**Issue by PoissonBallon** [at-internet/atinternet-ios-swift-sdk#10]
Hi guys, I can't build with ATInternet framework coz, xcode don't find the header : 

<img width="859" alt="screen shot 2016-08-19 at 10 47 53" src="https://cloud.githubusercontent.com/assets/8491808/17804112/6dd1b590-65fa-11e6-9471-a7a44f0f72cc.png">

**Comment by d-theo** [comment]
Hi, are you integrating from cocopods, carthage, from source ... ?

**Comment by PoissonBallon** [comment]
Cocoapods, and I compile with fastlane too ... same issue

**Comment by d-theo** [comment]
can you post your podfile ? Is your project in Swift or Objective-C ?
have you tried to clean / delete derived data / reboot xCode ? Sometimes xCode takes time to acknowledge Cocoapods libs...
Also do you think fastlane could be an issue ?

**Comment by PoissonBallon** [comment]
If i clean / delete derived data it's ok,
But it's strange, it's come back often :s  
But you can close. :) 
Thx guys

**Comment by d-theo** [comment]
uh, yes we noticed that Cocoapods + xCode is kinda buggy/slow, maybe due to the mix objc/swift in our framework

best regards

**Comment by iGranDav** [comment]
Hi,

I don't really think that you can close this issue. I've been encounting the same issue each time I am doing a `pod install`.

Currently using the latest version `ATInternet-iOS-Swift-SDK 2.2.4` on a full Swift project.

A clean isn't enough I need to clean the build directory. That's not a normal behavior.

**Comment by iGranDav** [comment]
Could you reopen the issue please? I still having it each time I am adding or changing a pod in my podfile and doing a `pod install`. This happens only with `ATInternet`

**Comment by bill350** [comment]
@d-theo Same issue for us here, could you please reopen the issue ? 
Thanks
