### ISSUE TITLE
Before the Swift 3.0 release, make a Swift 2.3 compatibility

### ISSUE THREAD

**Issue by bill350** [at-internet/atinternet-ios-swift-sdk#12]
Hi,

Did you already plan to make a release with Swift 2.3 compatibility changes before make the Swift 3 release compatibility (I see the branch swift3) ?

Because there is some projects which are using Swift 2.2 right know (and your Swift SDK). And those projects will not move immediately to Swift 3.0 on Xcode 8 but Swift 2.3 with Legacy Swift Version setting mode enabled.

Thanks.

**Comment by nsagnett** [comment]
Hi ! 

Swift 2.3 branch is now available

Regards

**Comment by ivanruizscm** [comment]
@nsagnett so when  swift 3 will be available?

**Comment by evixar** [comment]
Our master branch is already Swift 3 compatible (Tag 2.3.0)

Regards
