### ISSUE TITLE
Setting visitor category

### ISSUE THREAD

**Issue by lawicko** [at-internet/atinternet-ios-swift-sdk#15]
Hi,
I'm moving from the old version of your SDK to the new on, and I'm trying to set the visitor category on the tracker. My old code did it like so:
```
[atParam setVisitorIdentified:YES
                                andId:accountId
                          andCategory:@"1"];
```
In the new SDK I do this:
`ATInternet.sharedInstance.defaultTracker.identifiedVisitor.set(accountId, visitorCategory: 1)`

When I look into debugger, I see that the _at_ parameter is set correctly to the _accountId_, but there is nothing to indicate that the category was also set. How can I make sure the category is set correctly? Is the category parameter name _ac_ (this is what I'm seeing in the old SDK when inspecting the network traffic with the Charles proxy)?

**Comment by d-theo** [comment]
Yes indeed the category parameter name is ac :)

Also, if you want to move to the latest version you can check our new [tracker](https://github.com/at-internet/atinternet-apple-sdk) (beta)

**Comment by lawicko** [comment]
@d-theo Thanks for the answer, currently the requirement of Swift 3.0 holds me from using the latest tracker. In the meantime, I have discovered what was the problem for me - the interface in the tracker looks like this:
```
public func set(visitorId: String) -> Tracker {
        unset()
        save(HitParam.VisitorIdentifierText.rawValue, keyPersistent: IdentifiedVisitorHelperKey.Text.rawValue, value: visitorId)
        
        return self.tracker
    }
```
which means you unset the group when separately setting the visitorId. I guess this makes sense, so this topic can be closed ;)

**Comment by d-theo** [comment]
no problem, btw we also have a 2.3 branch ;)

**Comment by lawicko** [comment]
@d-theo Oh, ok, in this case I'm going to give it a go, thanks.
