### ISSUE TITLE
`UIApplication.shared.windows` accessed outside main thread

### ISSUE THREAD

**Issue by iGranDav** [at-internet/atinternet-ios-swift-sdk#20]
I am having a runtime issue regarding an access to `UIApplication.shared.windows` outside the main thread.

xcode 9 puts this in light with its runtime issues. Could you please review this implementation?

<img width="863" alt="atinternet_issue" src="https://user-images.githubusercontent.com/75418/31997176-4a809c06-b98b-11e7-93fc-22ee6d0a2d73.png">

**Comment by d-theo** [comment]
I will check on this :)
The problem here is that in rare cases, the window is not initialized since the call to enableDebugger can be done in the AppDelegate

**Comment by iGranDav** [comment]
Since this particular issue could occur only in debug and for the developer I suggest to test this case and prompt a `fatalError` to inform the developer to move the call.

```
guard !UIApplication.shared.windows.isEmpty else {
    fatalError("An initialized window is needed for ATInternet debugger to work, please move the `enableDebugger` after your first window initialization.")
}
```

This is just a suggestion.

**Comment by d-theo** [comment]
i'm going to try my luck with https://developer.apple.com/documentation/foundation/nsnotification.name/1621621-uiwindowdidbecomevisible else, I will implement something like you posted

**Comment by iGranDav** [comment]
That's an even better idea 👍 

If this is not enough, https://developer.apple.com/documentation/foundation/nsnotification.name/1621607-uiwindowdidbecomekey could probably work.

**Comment by d-theo** [comment]
btw I think the issue is on the wrong repo ;)

**Comment by iGranDav** [comment]
Yes it is! Sorry about that... We are indeed using the latest `ATInternet-Apple-SDK`

**Comment by d-theo** [comment]
No problem, I will close the issue when the fix is live

**Comment by iGranDav** [comment]
Thanks!
