### ISSUE TITLE
[iOS 8.1] Library not loaded Reason: image not found

### ISSUE THREAD

**Issue by Narayane** [at-internet/atinternet-ios-swift-sdk#3]
Hi,

I use your swift SDK 2.1.0 in a swift app targeting iOS 8+, this app is on appstore and everything works fine for iOS 8.4+ but a user under iOS 8.1.3 said than app has crashed during launching.

When I try to run my app on iOS 8.1 simulator, I have this error during launch screen display (I am not sure your SDK is the problem source but your framework is referenced in crash stack):

_dyld: Library not loaded: /System/Library/Frameworks/WatchKit.framework/WatchKit
  Referenced from: /Users/MyName/Library/Developer/Xcode/DerivedData/MyApp-goxhszyrrunwqoehznxluhrkvvmo/Build/Products/Debug-iphonesimulator/Tracker.framework/Tracker
  Reason: image not found_

I use Cocoapods so I tried to comment your pod and ran a "pod update" but strangely, when I reopen Xcode, I do not have import error on Tracker module use and so I have the same error even if I have commented your pod.

Can you help me ?

**Comment by ghost** [comment]
Hello,

I'm not able to reproduce your problem. Using the SDK 2.1.0 with CocoaPods, devices and simulators, everything is working fine on iOS 8.1 to iOS 9.

There is something odd though in your error message :
dyld: Library not loaded: /System/Library/Frameworks/**WatchKit.framework/WatchKit**

It's seems there is a wrong reference to our Tracker inside a WatchKit app or extension. Are you sure that you've checked all of your targets dependencies?

**Comment by d-theo** [comment]
Hi, can you describe steps to reproduce the bug ?
