### ISSUE TITLE
Custom var not added to gesture tracking

### ISSUE THREAD

**Issue by Serchinastico** [at-internet/atinternet-ios-swift-sdk#4]
Hi,

I'm moving to version 2.1.0 of the SDK from a really old version and I've found that custom vars aren't  being sent when tracking user gestures. This is the code I'm using:

``` swift
let tracker = ATInternet.sharedInstance.defaultTracker
tracker.customVars.add(2, "SomeValue", type: .App)
tracker.gestures.add("SomeScreen").sendTouch()
```

Tracking screen views are working fine though. I'm wondering if it's an expected behaviour or it's a bug.

Thanks for your time.

**Comment by ghost** [comment]
Hi,

Custom vars are only sent with a screen view.

**Comment by Serchinastico** [comment]
Hi @gbugniot 

Has this changed in a recent release? I'm seeing the custom bars being sent in version 1.6.0 (I know it's a really old one) and I'm afraid it might break our stats.

**Comment by ghost** [comment]
Yes, since 2.0.0.

In previous version, there was no tagging conformity checking algorithm in our code. But, even if custom vars was sent with gesture hits in 1.6.0, they were ignored by our backend.

**Comment by Serchinastico** [comment]
Gotcha,

Again, thanks for your time and quick responses!
