### ISSUE TITLE
Cathage build fails on 2.2.2

### ISSUE THREAD

**Issue by vhosune** [at-internet/atinternet-ios-swift-sdk#6]
There is a regression on cathage integration on 2.2.2

> <unknown>:0: error: filename "*.swift" used twice:

**Comment by evixar** [comment]
Hi,

We will check this problem soon and let you know when it's fixed

Regards

**Comment by d-theo** [comment]
Hi, 

thanks for reporting this issue, the carthage integration is now fixed

Regards,
