### ISSUE TITLE
Direct commit reference not possible in Podfile

### ISSUE THREAD

**Issue by orkoden** [at-internet/atinternet-ios-swift-sdk#9]
Directly referencing a commit isn't possible in a Podfile.

```
 pod 'ATInternet-iOS-Swift-SDK', git:'https://github.com/at-internet/atinternet-ios-swift-sdk.git', commit: 'abb2aded8b692079860e0ada564e7bc3edd1dcd1'
```

Running `pod install` leads to the following error.

```
Pre-downloading: `ATInternet-iOS-Swift-SDK` from `https://github.com/at-internet/atinternet-ios-swift-sdk.git`, commit `abb2aded8b692079860e0ada564e7bc3edd1dcd1`
[!] Unable to find a specification for 'ATInternet-iOS-Swift-SDK'.
```

There needs to be a `.podspec` file in the repository for this to work.

**Comment by d-theo** [comment]
I do think it's more a problem with Cocoapods not refreshing the podfile instantly. It usually takes few minutes/hours, the website still indicate 2.2.2 as the last version.

**Comment by orkoden** [comment]
Adding 
`pod 'ATInternet-iOS-Swift-SDK', '~> 2.2.3'
`
and then running 
`pod repo update`
`pod install`
works just fine.

Directly referencing the repository and a commit does not work.

**Comment by orkoden** [comment]
As the [documentation says](https://guides.cocoapods.org/using/the-podfile.html)

> The podspec file is expected to be in the root of the repo

**Comment by d-theo** [comment]
yes I just read it, but I'm not sure we will include the `.podspec` the in the repo as we have them all in one place internally. Maybe in the next releases ;)

**Comment by nsagnett** [comment]
Hi !

Podspec file is now available on root path

Regards
